[package]
name = "quite-elegant-typ"
version = "0.2.0"
categories = ["book"]
compiler = "0.14.2"
entrypoint = "lib.typ"

[template]
entrypoint = "main.typ"
path = "template"
thumbnail = "thumbnail.png"
